export const ADD_PLANET = 'ADD_PLANET';
export const REMOVE_PLANET = 'REMOVE_PLANET';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const UPDATE_SEARCH_RESULT = 'UPDATE_SEARCH_RESULT';
export const UPDATE_TIME_TAKEN = 'UPDATE_TIME_TAKEN';
export const RESET_ALL = 'RESET_ALL';